version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/:rw
      - ./setup-db.sql:/docker-entrypoint-initdb.d/init.sql